name: GitHub Pages

on:
  push:
    branches: ["master", "dev-prototype"]
  pull_request:
    branches: ["master", "dev-prototype"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Build
        run: |
          npm i pnpm -g
          rm -rf package-lock.json
          pnpm i
          pnpm i
          pnpm build
          echo "<html><meta http-equiv=\"refresh\" content=\"0;url=./docs/\"></html>" > ./index.html
          echo "mcd.js.org" > ./CNAME

      - name: Save changes
        run: |
          find . -name '.gitignore' -type f -print | xargs rm -rf
          git add .

      - name: Push Branch
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          amend: true
          force: true
