name: All test

on:
  push:
    branches: ["master", "dev-prototype"]
  pull_request:
    branches: ["master", "dev-prototype"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Init enviroument
        run: |
          npm i pnpm -g
          rm -rf package-lock.json
          pnpm i
          pnpm i
      - name: Test
        run: |
          pnpm test
      - name: Test cli
        run: |
          pnpm test:cli
          pnpm clear

  coverage:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - aocudeo
          - task-simple-limiter
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Push Branch
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: x-cov-${{ matrix.package }}
          amend: true
          force: true

      - name: Init enviroument
        run: |
          npm i pnpm -g
          rm -rf package-lock.json
          pnpm i
          pnpm i

      - name: Output coverage
        run: |
          cd packages/${{ matrix.package }}
          pnpm test
          pnpm nyc report -r=cobertura
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ github.token }}
          file: ./packages/${{ matrix.package }}/coverage/cobertura-coverage.xml
          format: cobertura
          git-branch: x-cov-${{ matrix.package }}

