name: All test

on:
  push:
    branches: ["master", "dev-prototype"]
  pull_request:
    branches: ["master", "dev-prototype"]

jobs:
  test-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Init enviroument
        run: |
          npm i pnpm -g
          pnpm i

      - name: Development test
        run: |
          pnpm turbo test-all

      - name: Production test
        run: |
          npm turbo prod-test-all
